version: '3.7'

services:
  proxy:
    image: nginx:alpine
    container_name: proxy
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: 'unless-stopped'
    networks:
      - backend
  server:
    build:
      context: ./
      target: development-build-stage
      dockerfile: Dockerfile
    container_name: server
    ports:
      - '3000:3000'
    volumes:
      - ./:/app
      - /app/node_modules
    restart: 'unless-stopped'
    networks:
      - backend
    links:
      - mysql
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7
    container_name: mysqldb
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
      # MYSQL_DATABASE: sequelize_demo
    ports:
      - '3307:3306'
    networks:
      - backend
    volumes:
      - /Users/jackie/docker-temp/mysql/conf:/etc/conf
      - /Users/jackie/docker-temp/mysql/data:/var/lib/mysql
      - /Users/jackie/docker-temp/mysql/log:/var/log/mysql

networks:
  backend:
    driver: bridge

volumes:
  data:
    driver: local
